config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :options
  resources :deliveryoptions
  resources :bookings

  get 'all' => 'bookings#all', as: :all
  post 'cleanup' => 'bookings#cleanup', as: :cleanup

  resources :users do
    collection { get :search, :request_reset, :reset_password }
    collection { post :request_reset, :reset_password }
  end
  get '/users/:id/reset_password/:onetimetoken(.:format)' => 'users#reset_password', as: 'reset'

  resources :sessions
  post 'logout' => 'sessions#destroy'

  get '/about' => 'application#about'

  root 'bookings#index'

end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base

  attr_accessor :passwd_upd
  after_initialize :set_initial_password

  before_validation :downcase_email
  VALID_EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/

  has_secure_password
  belongs_to :company
  # accepts_nested_attributes_for :bookings

  validates_presence_of :email, :company_id, :vname, :nname, :tel
  validates :email, uniqueness: true, format: {with: VALID_EMAIL_REGEX }

  def full_name
    "#{vname} #{nname}"
  end

  def is_admin
    self.role == 1 || self.role == 2
  end

  def ist_bestatter?
    self.role == 3
  end

  def set_initial_password
    unless self.password_digest
      passwd = SecureRandom.hex
      self.password = passwd
      self.password_confirmation = passwd
    end
  end

  def downcase_email
    self.email = email.downcase if self.email.present?
  end

  def set_onetimetoken
    self.onetimetoken = SecureRandom.hex
    self.save(validate: false)
  end

  def reset_onetimetoken
    self.onetimetoken = nil
    self.save(validate: false)
  end

  scope :bestatter,-> {where(role: 3)}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :logged_in, only: [:reset_password, :request_reset]
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @planer = User.where(role: 2).order('nname DESC')
    @bestatter = User.where(role: 3).order('nname DESC')
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @user.role = 3
    @show_password_fields = false
  end

  # GET /users/1/edit
  def edit
  end

  def request_reset
    if params[:email]
      if User.where(email: params[:email]).first
        @user = User.where(email: params[:email]).first
        @user.set_onetimetoken
        UserMailer.password_reset(@user).deliver_now
        redirect_to new_session_path, notice: t(:email_sent)
      else
        redirect_to request_reset_users_path, alert: t(:unknown_email)
      end
    end
  end

  def reset_password
    @user = User.find(params[:id])
    if @user.onetimetoken == params[:onetimetoken]
      session[:user_id] = @user.id
      @current_user = @user
      @user.reset_onetimetoken
    else
      redirect_to new_session_path, alert: t(:wrong_token)
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.set_onetimetoken
    respond_to do |format|
      if @user.save
        # UserMailer.welcome_email(@user).deliver_now
        format.html { redirect_to @user, notice: 'Der Bestatter / Planer wurde angelegt und muss sich nun ein Passwort geben.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        if @user.passwd_upd
          @user.reset_onetimetoken
          format.html { redirect_to root_url, notice: t(:password_changed) }
        else
          format.html { redirect_to @user, notice: 'Die Daten wurden aktualisiert.' }
          format.json { render :show, status: :ok, location: @user }
        end
      else
        if @user.passwd_upd
          flash[:warning] = t(:password_not_changed)
          format.html { render :reset_password }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Der Bestatter / Planer wurde vom System gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :vname, :nname, :password_digest, :password, :password_confirmation, :passwd_upd, :company_id, :hnr, :plz, :strasse, :ort, :tel, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
  <tr>
    <td colspann="2" class="field">
      <%= f.label "E-Mail (= Login)" %><br>
      <%= f.text_field :email %>
    </td>
  </tr>
  <tr>
    <td colspann="2" class="field">
      <%= f.label "Firma" %> (oder erst <%= link_to "neue Firma anlegen?", new_company_path %>)<br>
      <%= f.collection_select(:company_id, Company.all, :id, :name) %>
    </td>
  </tr>
  <tr>
    <td class="field">
      <%= f.label :vname %><br>
      <%= f.text_field :vname %>
    </td>
    <td class="field">
      <%= f.label :nname %><br>
      <%= f.text_field :nname %>
    </td>
  </tr>
  <tr>
    <td class="field">
      <%= f.label :strasse %><br>
      <%= f.text_field :strasse %>
    </td>
    <td class="field">
      <%= f.label :hnr %><br>
      <%= f.text_field :hnr %>
    </td>
  </tr>
  <tr>
    <td class="field">
      <%= f.label :plz %><br>
      <%= f.text_field :plz %>
    </td>
    <td class="field">
      <%= f.label :ort %><br>
      <%= f.text_field :ort %>
    </td>
  </tr>
  <tr>
    <td class="field">
      <%= f.label :tel %><br>
      <%= f.text_field :tel %>
    </td>
    <td class="field">
      <%= f.label :role %><br>
      <%= f.select :role, ([["Planer", 2], ["Bestatter", 3]]) %>
    </td>
  </tr>
  <tr>
    <td class="actions">
      <%= f.submit %>
    </td>
    <td>
      <% unless current_page?(new_user_path) %>
        <%= link_to 'Bestatter / Planer löschen', @user, method: :delete, data: { confirm: 'Sind Sie sicher?' }, style: "color:darkred;" %>
      <% end %>
    </td>
  </tr>
  </table>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<table class="liste">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Firma</th>
      <th>Telefon</th>
      <th>E-Mail</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th class="interim">Bestatter</th>
      <th class="interim" colspan="5"></th>
    </tr>
    <% @bestatter.each do |user| %>
      <tr>
        <td class="interim"></td>
        <td><%= link_to "#{user.nname}, #{user.vname}", edit_user_path(user) %></td>
        <td><%= user.company.name %></td>
        <td><%= user.tel %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
    <tr>
      <th class="interim">Planer</th>
      <th class="interim" colspan="5"></th>
    </tr>
    <% @planer.each do |user| %>
      <tr>
        <td class="interim"></td>
        <td><%= link_to "#{user.nname}, #{user.vname}", edit_user_path(user) %></td>
        <td><%= user.company.name %></td>
        <td><%= user.tel %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'neuer Bestatter / Planer', new_user_path %>

app/views/users/new.html.erb
<h1>Neuer Bestatter / Planer</h1>

<%= render 'form' %>

app/views/users/request_reset.html.erb
<h2>Passwort-Reset</h2>
<p>Bitte geben Sie die registrierte E-Mail-Adresse an. Ihnen wird dann ein Link zum Zürücksetzen des Passworts zugeschickt.
<div class="form-box">
<%= form_tag request_reset_users_path do %>
	<label><%= t("activerecord.attributes.user.email") %></label>
	<%= text_field_tag :email, params[:email] %></p>
  <p><%= submit_tag "Link anfordern" %></p>
<% end %>
</div>

app/views/users/reset_password.html.erb
<h2>Passwortreset für <%= @user.vname + " " + @user.nname %></h2>
<div class="form-box">
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <p><%= t(:error_message, count: @user.errors.count) %></p>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
   	<p>
    	<strong><%= t("new_password") %></strong><br>
    	<%= f.password_field :password, class: "text_field" %>
  	</p>
  	<p>
    	<strong><%= t("activerecord.attributes.user.password_confirmation") %></strong><br>
    	<%= f.password_field :password_confirmation, class: "text_field" %>
  	</p>
    <%= hidden_field_tag(:onetimetoken, @user.onetimetoken) %>
    <%= f.hidden_field :passwd_upd, value: true %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%  @user.role == 2 ? rolle = "Planer" : rolle = "Bestatter" %>
<article class="vcard">
<h2><%=  @user.vname + " " +  @user.nname %></h2>
<aside class="subheading">(Funktion: <%= rolle %> )</aside>
<p>
  <%= @user.company.name %>
</p>

<p>
  <%= @user.strasse + " " + @user.hnr %><br>
  <%= @user.plz + " " + @user.ort %>
</p>

<p>
  <strong>Tel:</strong> <%= @user.tel %><br>
  <strong>E-Mail:</strong> <%= @user.email %>
</p>
</article>

<%= link_to("Datensatz zum #{rolle} drucken | ", "javascript:print()", class: "no_print") %>
<%= link_to 'bearbeiten', edit_user_path(@user), class: "no_print" %>