config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :options
  resources :deliveryoptions
  resources :bookings

  get 'all' => 'bookings#all', as: :all
  post 'cleanup' => 'bookings#cleanup', as: :cleanup

  resources :users do
    collection { get :search, :request_reset, :reset_password }
    collection { post :request_reset, :reset_password }
  end
  get '/users/:id/reset_password/:onetimetoken(.:format)' => 'users#reset_password', as: 'reset'

  resources :sessions
  post 'logout' => 'sessions#destroy'

  get '/about' => 'application#about'

  root 'bookings#index'

end

app/models/deliveryoption.rb
# encoding: UTF-8
class Deliveryoption < ActiveRecord::Base
  has_many :bookings
end

app/controllers/deliveryoptions_controller.rb
class DeliveryoptionsController < ApplicationController
  before_action :set_deliveryoption, only: [:show, :edit, :update, :destroy]

  # GET /deliveryoptions
  # GET /deliveryoptions.json
  def index
    @deliveryoptions = Deliveryoption.all
  end

  # GET /deliveryoptions/1
  # GET /deliveryoptions/1.json
  def show
  end

  # GET /deliveryoptions/new
  def new
    @deliveryoption = Deliveryoption.new
  end

  # GET /deliveryoptions/1/edit
  def edit
  end

  # POST /deliveryoptions
  # POST /deliveryoptions.json
  def create
    @deliveryoption = Deliveryoption.new(deliveryoption_params)

    respond_to do |format|
      if @deliveryoption.save
        format.html { redirect_to @deliveryoption, notice: 'Deliveryoption was successfully created.' }
        format.json { render :show, status: :created, location: @deliveryoption }
      else
        format.html { render :new }
        format.json { render json: @deliveryoption.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deliveryoptions/1
  # PATCH/PUT /deliveryoptions/1.json
  def update
    respond_to do |format|
      if @deliveryoption.update(deliveryoption_params)
        format.html { redirect_to @deliveryoption, notice: 'Deliveryoption was successfully updated.' }
        format.json { render :show, status: :ok, location: @deliveryoption }
      else
        format.html { render :edit }
        format.json { render json: @deliveryoption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveryoptions/1
  # DELETE /deliveryoptions/1.json
  def destroy
    @deliveryoption.destroy
    respond_to do |format|
      format.html { redirect_to deliveryoptions_url, notice: 'Deliveryoption was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deliveryoption
      @deliveryoption = Deliveryoption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deliveryoption_params
      params.require(:deliveryoption).permit(:option)
    end
end

app/helpers/deliveryoptions_helper.rb
module DeliveryoptionsHelper
end

app/views/deliveryoptions/_form.html.erb
<%= form_for(@deliveryoption) do |f| %>
  <% if @deliveryoption.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deliveryoption.errors.count, "error") %> prohibited this deliveryoption from being saved:</h2>

      <ul>
      <% @deliveryoption.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :option %><br>
    <%= f.text_field :option %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deliveryoptions/edit.html.erb
<h1>Editing Deliveryoption</h1>

<%= render 'form' %>

<%= link_to 'Show', @deliveryoption %> |
<%= link_to 'Back', deliveryoptions_path %>

app/views/deliveryoptions/index.html.erb
<h1>Listing Deliveryoptions</h1>

<table>
  <thead>
    <tr>
      <th>Option</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deliveryoptions.each do |deliveryoption| %>
      <tr>
        <td><%= deliveryoption.option %></td>
        <td><%= link_to 'Show', deliveryoption %></td>
        <td><%= link_to 'Edit', edit_deliveryoption_path(deliveryoption) %></td>
        <td><%= link_to 'Destroy', deliveryoption, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deliveryoption', new_deliveryoption_path %>

app/views/deliveryoptions/new.html.erb
<h1>New Deliveryoption</h1>

<%= render 'form' %>

<%= link_to 'Back', deliveryoptions_path %>

app/views/deliveryoptions/show.html.erb
<p>
  <strong>Option:</strong>
  <%= @deliveryoption.option %>
</p>

<%= link_to 'Edit', edit_deliveryoption_path(@deliveryoption) %> |
<%= link_to 'Back', deliveryoptions_path %>