config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :options
  resources :deliveryoptions
  resources :bookings

  get 'all' => 'bookings#all', as: :all
  post 'cleanup' => 'bookings#cleanup', as: :cleanup

  resources :users do
    collection { get :search, :request_reset, :reset_password }
    collection { post :request_reset, :reset_password }
  end
  get '/users/:id/reset_password/:onetimetoken(.:format)' => 'users#reset_password', as: 'reset'

  resources :sessions
  post 'logout' => 'sessions#destroy'

  get '/about' => 'application#about'

  root 'bookings#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buchungssystem FBV Chur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="content">
    <header class="main">
      <aside class="right">
        <%= (button_to "Abmelden", logout_path, class: "no_print") if @current_user %>
      </aside>
      <h1>Buchungssystem des Feuerbestattungsvereins Chur</h1>
      <aside class="menu">
        <ul>
        <% if @current_user %>
          <li><%= link_to t(:home), root_path %></li>
          <li><%= link_to t(:bookings), all_path %></li>
          <% if @current_user.is_admin %>
            <li><%= link_to t(:companies), companies_path %></li>
            <li><%= link_to t(:users), users_path %></li>
            <li><%= link_to "Einstellungen / Ausnahmen", options_path %></li>
          <% end %>
        <% else %>
          <% if current_page?(:about) %>
            <li><%= link_to t(:home), root_path %></li>
          <% else %>
            <li><%= link_to t(:reset), request_reset_users_path %></li>
          <% end %>
        <% end %>
        </ul>
      </aside>
    </header>
    <article class="main">
    <% if @deletables_count != nil && @deletables_count > 0 %>
    <aside id="cleanup_bookings" class="right">
        Es gibt <%= t(:deletable, count: @deletables_count) %>.
        <%= button_to "alte Buchungen löschen", cleanup_path %>
      </aside>
      <% end %>
      <h2><%= @title ||= "" %></h2>
      <% flash.each do |name, msg| %> <%= content_tag :div, msg, id: name %> <% end %>
    </article>
    
    <section class="main">
      <%= yield %>
    </section>
    <footer class="no_print">
      <p class="right"><%= link_to "about", about_path, class: "dezent" %></p>
      <p>Bei Fragen kontaktieren Sie uns bitte unter der Telefonnummer: +41 81 252 44 62</p>
    </footer>
  </div>
</body>
</html>